#!/usr/bin/python
# -*- coding: utf-8 -*-

#creating SQL tables

import psycopg2
import sys

con = None

try:

    con = psycopg2.connect("dbname='fec' user='adammorris'")

    cur = con.cursor()

    cur.execute("CREATE TABLE Cmte_Master(cycle SMALLINT,CMTE_ID VARCHAR (9),CMTE_NM VARCHAR (200),TRES_NM VARCHAR (90),CMTE_ST1 VARCHAR (34),CMTE_ST2 VARCHAR (34),CMTE_CITY VARCHAR (30),CMTE_ST VARCHAR (2),CMTE_ZIP VARCHAR (9),CMTE_DSGN VARCHAR (1),CMTE_TP VARCHAR (1),CMTE_PTY_AFFILIATION VARCHAR (3),CMTE_FILING_FREQ VARCHAR (1),ORG_TP VARCHAR (1),CONNECTED_ORG_NM VARCHAR (200),CAND_ID VARCHAR (9))")

    cur.execute("CREATE TABLE Can_Master(cycle SMALLINT,CAND_ID VARCHAR (9) NOT NULL,CAND_NAME VARCHAR (200),CAND_PTY_AFFILIATION VARCHAR (3),CAND_ELECTION_YR SMALLINT,CAND_OFFICE_ST VARCHAR (2),CAND_OFFICE VARCHAR (1),CAND_OFFICE_DISTRICT VARCHAR (2),CAND_ICI VARCHAR (1),CAND_STATUS VARCHAR (1),CAND_PCC VARCHAR (9),CAND_ST1 VARCHAR (34),CAND_ST2 VARCHAR (34),CAND_CITY VARCHAR (30),CAND_ST VARCHAR (2),CAND_ZIP VARCHAR (9))")
    cur.execute("CREATE TABLE cmte_cand_link(cycle SMALLINT,CAND_ID VARCHAR (9) NOT NULL,CAND_ELECTION_YR SMALLINT NOT NULL,FEC_ELECTION_YR SMALLINT NOT NULL,CMTE_ID VARCHAR (9),CMTE_TP VARCHAR (1),CMTE_DSGN VARCHAR (1),LINKAGE_ID NUMERIC (12) NOT NULL)")
    cur.execute("CREATE TABLE contr_to_cmte_from_cmtes(cycle SMALLINT,CMTE_ID VARCHAR (9) NOT NULL,AMNDT_IND VARCHAR (1),RPT_TP VARCHAR (3),TRANSACTION_PGI VARCHAR (5),IMAGE_NUM VARCHAR (18),TRANSACTION_TP VARCHAR (3),ENTITY_TP VARCHAR (3),NAME VARCHAR (200),CITY VARCHAR (30),STATE VARCHAR (2),ZIP_CODE VARCHAR (9),EMPLOYER VARCHAR (38),OCCUPATION VARCHAR (38),TRANSACTION_DT VARCHAR (8),TRANSACTION_AMT NUMERIC (14,2),OTHER_ID VARCHAR (9),TRAN_ID VARCHAR (32),FILE_NUM NUMERIC (22),MEMO_CD VARCHAR (1) ,MEMO_TEXT VARCHAR (100),SUB_ID NUMERIC (19) NOT NULL)")

    cur.execute("CREATE TABLE opp_exps(cycle smallint,CMTE_ID VARCHAR(9) NOT NULL,AMNDT_IND VARCHAR(1),RPT_YR SMALLINT,RPT_TP VARCHAR(3),IMAGE_NUM VARCHAR(18),LINE_NUM VARCHAR,FORM_TP_CD VARCHAR(8),SCHED_TP_CD VARCHAR(8),NAME VARCHAR(200),CITY VARCHAR(30),STATE VARCHAR(2),ZIP_CODE VARCHAR(9),TRANSACTION_DT DATE,TRANSACTION_AMT NUMERIC,TRANSACTION_PGI VARCHAR(5),PURPOSE VARCHAR(100),CATEGORY VARCHAR(3),CATEGORY_DESC VARCHAR (40),MEMO_CD VARCHAR (1),MEMO_TEXT VARCHAR (100),ENTITY_TP
    VARCHAR(3),SUB_ID NUMERIC (19) NOT NULL,FILE_NUM NUMERIC (7),TRAN_ID VARCHAR(32),BACK_REF_TRAN_ID VARCHAR(32),Blank VARCHAR (1))")
    con.commit()


except psycopg2.DatabaseError as e:

    if con:
        con.rollback()

    print (e)
    sys.exit(1)


finally:

    if con:
        con.close()
